import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../api.js";

export default function AddBook() {
  const [title, setTitle] = useState("");
  const [author, setAuthor] = useState("");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState(null);
  const navigate = useNavigate();

  async function onSubmit(e) {
    e.preventDefault();
    setBusy(true);
    setError(null);
    try {
      const book = await api.addBook(title, author);
      navigate(`/books/${book.id}`);
    } catch (err) {
      setError(err.message);
    } finally {
      setBusy(false);
    }
  }

  return (
    <form className="add-book-form" onSubmit={onSubmit}>
      <h2>Add a book</h2>
      <p className="hint">
        The summary and chapter highlights are generated by an LLM from its general
        knowledge of the book — this can take 10–20 seconds.
      </p>
      <label>
        Title
        <input value={title} onChange={(e) => setTitle(e.target.value)} required />
      </label>
      <label>
        Author
        <input value={author} onChange={(e) => setAuthor(e.target.value)} required />
      </label>
      {error && <p className="error">{error}</p>}
      <button type="submit" disabled={busy}>
        {busy ? "Generating…" : "Add book"}
      </button>
    </form>
  );
}
